### ISSUE TITLE
[1.1.0] Manual or description needed

### ISSUE THREAD

**Issue by scytero** [N1Ran/RandomWeatherPlugin#1]
Currently, there is not too much of information to find on how to configure the plugin. Is it string or ID based? What is a CustomWeatherRule? How/Where to retrieve Planet IDs?

I really would like to have more descriptions or at least some example on how to work with the plugin.

Thanks a lot!

**Comment by N1Ran** [comment]
https://github.com/N1Ran/RandomWeatherPlugin/wiki/Sample-Config
